### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by gaoyifan** [ly0/baidu-fuse#1]
您好，我在尝试`python baidufuse.py USERNAME PASSWORD mnt`后出现以下错误：
Traceback (most recent call last):
  File "baidufuse.py", line 404, in <module>
    FUSE(BaiduFS(sys.argv[1],sys.argv[2]),sys.argv[3],foreground=True, nonempty=True)
  File "baidufuse.py", line 85, in **init**
    self.disk = PCS(username, password)
  File "/usr/local/lib/python2.7/dist-packages/baidupcsapi/api.py", line 400, in **init**
    super(PCS, self).**init**(username, password, api_template, captcha_func=captcha_callback)
  File "/usr/local/lib/python2.7/dist-packages/baidupcsapi/api.py", line 135, in **init**
    self._initiate()
  File "/usr/local/lib/python2.7/dist-packages/baidupcsapi/api.py", line 181, in _initiate
    self._login()
  File "/usr/local/lib/python2.7/dist-packages/baidupcsapi/api.py", line 278, in _login
    captcha = self._get_captcha(code_string)
  File "/usr/local/lib/python2.7/dist-packages/baidupcsapi/api.py", line 220, in _get_captcha
    jpeg = self.session.get(url).content
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ResponseNotReady())
看起来好像是登陆阶段出现了错误？

我的环境：
ubuntu 14.04.2 x64
python 2.7.6

谢谢

**Comment by ly0** [comment]
似乎是，我明天回去看一下
